CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    email text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_users" PRIMARY KEY (id)
);


CREATE TABLE sessions (
    id uuid NOT NULL DEFAULT (gen_random_uuid()),
    user_id bigint NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_sessions" PRIMARY KEY (id),
    CONSTRAINT "FK_sessions_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);


CREATE INDEX "IX_sessions_user_id" ON sessions (user_id);


CREATE UNIQUE INDEX "IX_users_email" ON users (email);


