CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    email text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_users" PRIMARY KEY (id)
);


CREATE TABLE audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    action text NOT NULL,
    table_name text NOT NULL,
    record_id text,
    occurred_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_audit_logs" PRIMARY KEY (id),
    CONSTRAINT "FK_audit_logs_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT
);


CREATE TABLE sessions (
    id uuid NOT NULL DEFAULT (gen_random_uuid()),
    user_id bigint NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_sessions" PRIMARY KEY (id),
    CONSTRAINT "FK_sessions_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);


CREATE INDEX "IX_audit_logs_occurred_at" ON audit_logs (occurred_at);


CREATE INDEX "IX_audit_logs_table_name_record_id" ON audit_logs (table_name, record_id);


CREATE INDEX "IX_audit_logs_user_id" ON audit_logs (user_id);


CREATE INDEX "IX_sessions_user_id" ON sessions (user_id);


CREATE UNIQUE INDEX "IX_users_email" ON users (email);


